---
title: "Results"
author: "Krishnakanta Maity"
date: "2022-12-23"
output: pdf_document
---

```{r warning=FALSE}
# Clear environment
rm(list = ls())
graphics.off()

# Load the libraries
library(tidyverse)
library(lfe)
library(stargazer)

# Set working directory
# setwd("D:/Project/SummerProject/notebook/")
setwd("G:/Other computers/HP/SummerProject/notebook")
# Load the data
data <- read.csv('./../data/final_result.csv')
# Change the variable type
data$banker_name <- factor(data$banker_name, )
data$vulnerable <- factor(data$vulnerable)
data$type <- factor(data$type)
data$company_name <- factor(data$company_name)
data$time <- factor(data$time)
data$bank_prod_code <- factor(as.numeric(data$banker_name)*data$nic_prod_code)

sapply(data, function(x){length(unique(x))})
```

\newpage

```{r warning=FALSE}
# NSKEW
model1 <- felm(nskew ~ mes + time + mes*time | banker_name | 0 | banker_name + nic_prod_code, data = data)
model2 <- felm(nskew ~ mes + time + mes*time | nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model3 <- felm(nskew ~ mes + time + mes*time | bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model4 <- felm(nskew ~ mes + time + mes*time | banker_name + nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model5 <- felm(nskew ~ mes + time + mes*time | banker_name + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model6 <- felm(nskew ~ mes + time + mes*time | nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model7 <- felm(nskew ~ mes + time + mes*time | banker_name + nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)

stargazer(model1, model2, model3, model4, model5, model6, model7,
          type = 'text', float = TRUE, font.size = "small",
          dep.var.labels = c('NSKEW: Crash Risk Measure'), 
          title = 'Table 1: Result for NSKEW measure (Without controls)',
          covariate.labels = c('MES', 'Post', 'MES:Post'), align = TRUE,
          no.space = TRUE, keep.stat = c('n','rsq'))
```

\newpage 

```{r warning=FALSE}
model1 <- felm(nskew ~ mes + time + mes*time + roa + leverage + ic_nskew | banker_name | 0 | banker_name + nic_prod_code, data = data)
model2 <- felm(nskew ~ mes + time + mes*time + roa + leverage + ic_nskew | nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model3 <- felm(nskew ~ mes + time + mes*time + roa + leverage + ic_nskew | bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model4 <- felm(nskew ~ mes + time + mes*time + roa + leverage + ic_nskew | banker_name + nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model5 <- felm(nskew ~ mes + time + mes*time + roa + leverage + ic_nskew | banker_name + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model6 <- felm(nskew ~ mes + time + mes*time + roa + leverage + ic_nskew | nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model7 <- felm(nskew ~ mes + time + mes*time + roa + leverage + ic_nskew | banker_name + nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)

stargazer(model1, model2, model3, model4, model5, model6, model7,
          type = 'text', float = TRUE, font.size = "small",
          dep.var.labels = c('NSKEW: Crash Risk Measure'), 
          title = 'Table 2: Result for NSKEW measure (With controls)',
          covariate.labels = c('MES', 'Post', 'ROA', 'Leverage', 'NSKEW (t-1)', 'MES:Post'), align = TRUE,
          no.space = TRUE, keep.stat = c('n','rsq'))
```

\newpage

```{r warning=FALSE}
# DUVOL
model1 <- felm(duvol ~ mes + time + mes*time | banker_name | 0 | banker_name + nic_prod_code, data = data)
model2 <- felm(duvol ~ mes + time + mes*time | nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model3 <- felm(duvol ~ mes + time + mes*time | bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model4 <- felm(duvol ~ mes + time + mes*time | banker_name + nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model5 <- felm(duvol ~ mes + time + mes*time | banker_name + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model6 <- felm(duvol ~ mes + time + mes*time | nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model7 <- felm(duvol ~ mes + time + mes*time | banker_name + nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)

stargazer(model1, model2, model3, model4, model5, model6, model7,
          type = 'text', float = TRUE, font.size = "small",
          dep.var.labels = c('DUVOL: Crash Risk Measure'), 
          title = 'Table 3: Result for DUVOL measure (Without controls)',
          covariate.labels = c('MES', 'Post', 'MES:Post'), align = TRUE,
          no.space = TRUE, keep.stat = c('n','rsq'))
```

\newpage

```{r warning=FALSE}
model1 <- felm(duvol ~ mes + time + mes*time + roa + leverage + ic_duvol | banker_name | 0 | banker_name + nic_prod_code, data = data)
model2 <- felm(duvol ~ mes + time + mes*time + roa + leverage + ic_duvol | nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model3 <- felm(duvol ~ mes + time + mes*time + roa + leverage + ic_duvol | bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model4 <- felm(duvol ~ mes + time + mes*time + roa + leverage + ic_duvol | banker_name + nic_prod_code | 0 | banker_name + nic_prod_code, data = data)
model5 <- felm(duvol ~ mes + time + mes*time + roa + leverage + ic_duvol | banker_name + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model6 <- felm(duvol ~ mes + time + mes*time + roa + leverage + ic_duvol | nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)
model7 <- felm(duvol ~ mes + time + mes*time + roa + leverage + ic_duvol | banker_name + nic_prod_code + bank_prod_code | 0 | banker_name + nic_prod_code, data = data)

stargazer(model1, model2, model3, model4, model5, model6, model7,
          type = 'text', float = TRUE, font.size = "small",
          dep.var.labels = c('DUVOL: Crash Risk Measure'), 
          title = 'Table 4: Result for DUVOL measure (With controls)',
          covariate.labels = c('MES', 'Post', 'ROA', 'Leverage', 'DUVOL (t-1)', 'MES:Post'), align = TRUE,
          no.space = TRUE, keep.stat = c('n','rsq'))

```

